<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cshtml</string>
	</array>
	<key>name</key>
	<string>Razor</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(@?([a-zA-Z0-9]+)?)(\s[a-zA-Z0-9]+)?(
|
)?(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.cshtml</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.cshtml</string>
				</dict>
			</dict>
			<key>comments</key>
			<string>Simple multi-line code section</string>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.cshtml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>section.embedded.source.cshtml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(@?([a-zA-Z0-9]+)?)(\s[a-zA-Z0-9]+)?(
|
)?(\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.cshtml</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.cshtml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.cshtml</string>
						</dict>
					</dict>
					<key>name</key>
					<string>section.embedded.source.cshtml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>'</string>
							<key>name</key>
							<string>string.quoted.single.cshtml</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#embedded-code</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.cs</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.html.basic</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single.cshtml</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded-code</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@[a-zA-Z0-9]+)(\s?)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>section.embedded.begin.cshtml</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.cshtml</string>
				</dict>
			</dict>
			<key>comments</key>
			<string>Covers single line Razor tags</string>
			<key>end</key>
			<string>(\n|\s)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.source.cshtml</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.namespace.source.cshtml</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(([a-zA-Z0-9]+)(\.)?)+?</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded-code</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.cs</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.handlebars</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.handlebars</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>begin</key>
			<string>@\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.source.cshtml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*@</string>
			<key>name</key>
			<string>comment.block.cshtml</string>
		</dict>
		<key>embedded-code</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.cshtml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.source.cshtml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(@?[a-zA-Z0-9]+)(\.([a-zA-Z0-9]+))?</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.cshtml</string>
	<key>uuid</key>
	<string>4f902f1e-9ac6-497d-a110-6d450bfd5b0b</string>
</dict>
</plist>
